name: TDR Run Graphql Schema Check
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: sbt/setup-sbt@6bec67c98f542b9e17369bfca0ec822ac1363194 # v1.1.19
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@4cce7fa069b9dbecddbdacd9350f66adc50ac815 # v0.0.22
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@4cce7fa069b9dbecddbdacd9350f66adc50ac815 # v0.0.22
        if: failure()
        with:
          message: ":warning: Secrets found in repository ${{ inputs.repo-name }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Check schema
        run: |
          mkdir -p src/main/resources/
          wget -O src/main/resources/schema.graphql https://raw.githubusercontent.com/nationalarchives/tdr-consignment-api/master/schema.graphql
          sbt graphqlCodegen
